export const CHAIN_ID = '2040effda178d4fffff5eab7a915d4019879f5205cc5392e4bcced2b6edda0cd';
export const ADDRESS_PREFIX = 'VIZ';

// Index = position in viz-js-lib operation.st_operations (operations.js).
export const OP_TYPE_IDS: Readonly<Record<string, number>> = {
  transfer: 2,
  transfer_to_vesting: 3,
  withdraw_vesting: 4,
  account_update: 5,
  validator_update: 6,
  account_validator_vote: 7,
  account_validator_proxy: 8,
  custom: 10,
  set_withdraw_vesting_route: 11,
  request_account_recovery: 12,
  recover_account: 13,
  change_recovery_account: 14,
  escrow_transfer: 15,
  escrow_dispute: 16,
  escrow_release: 17,
  escrow_approve: 18,
  delegate_vesting_shares: 19,
  account_create: 20,
  account_metadata: 21,
  proposal_create: 22,
  proposal_update: 23,
  proposal_delete: 24,
  chain_properties_update: 25,
  committee_worker_create_request: 35,
  committee_worker_cancel_request: 36,
  committee_vote_request: 37,
  create_invite: 43,
  claim_invite_balance: 44,
  invite_registration: 45,
  versioned_chain_properties_update: 46,
  award: 47,
  set_paid_subscription: 50,
  paid_subscribe: 51,
  set_account_price: 54,
  set_subaccount_price: 55,
  buy_account: 56,
  use_invite_balance: 58,
  fixed_award: 60,
  target_account_sale: 61,
  set_reward_sharing: 64,
  // Deprecated aliases share the validator op ids:
  account_witness_vote: 7,
  account_witness_proxy: 8,
  witness_update: 6,
};
